//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPROJECT.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tExercise
    {
        public int fID { get; set; }

        [DisplayName("日期")]
        [Required]
        public string fEX_DATE { get; set; }

        [DisplayName("項目")]
        [Required]
        public string fEX_TYPE { get; set; }

        [DisplayName("肌群")]
        [Required]
        public string fEX_MUSCLE { get; set; }

        [DisplayName("動作")]
        [Required]
        public string fEX_METHOD { get; set; }

        [DisplayName("次數")]
        [Required]
        public int? fEX_TIMES { get; set; }

        [DisplayName("公斤")]
        [Required]
        public decimal? fEX_KG { get; set; }

        [DisplayName("組數")]
        [Required]
        public int? fEX_SETS { get; set; }

        [DisplayName("登入帳號")]
        public string fEX_UserID { get; set; }
    }
}
