//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPROJECT.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tISTXN
    {
        public int fID { get; set; }

        [DisplayName("日期")]
        [Required]
        public string fTXN_DATE { get; set; }

        [DisplayName("類別")]
        [Required]
        public string fTXN_TYPE { get; set; }

        [DisplayName("描述")]
        [Required]
        public string fTXN_DESC { get; set; }

        [DisplayName("金額")]
        [Required]
        public decimal? fTXN_AMT { get; set; }

        [DisplayName("交易方式")]
        [Required]
        public string fTXN_OPTION { get; set; }

        [DisplayName("登入帳號")]
        [Required]
        public string fTXN_UserID { get; set; }

    }
}
