//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPROJECT.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        public int fID { get; set; }

        [DisplayName("帳號")]
        [Required]
        public string fMem_UserID { get; set; }

        [DisplayName("密碼")]
        [Required]
        public string fMem_Pwd { get; set; }

        [DisplayName("姓名")]
        [Required]
        public string fMem_Name { get; set; }

        [DisplayName("信箱")]
        [Required]
        [EmailAddress]
        public string fMem_Email { get; set; }

        [DisplayName("性別")]
        [Required]
        public string fMem_Gender { get; set; }

        [DisplayName("出生日期")]
        [Required]
        public string fMem_Birthday { get; set; }
    }
}
